// COM data keys
#define COLOR_KEY "COLOR"
#define BRIGHTNESS_KEY "BRIGHTNESS"
#define SAVE_KEY "SAVE"
#define RESET_KEY "RESET"
#define SUCCESS_KEY "SUCCESS"

// EEPROM
#define EEPROM_INIT_KEY 0x42
#define EEPROM_INIT 0
#define EEPROM_R 1
#define EEPROM_G 2
#define EEPROM_B 3
#define EEPROM_BRIGTHNESS 4
